fix numpy warnings
alexlancaster/pypop pull request #113
Opened 2023-08-25 23:45 UTC by alexlancaster

@rsingle I noticed that the calls to `math.sqrt` were producing `numpy` warnings.  I think this is due to being passed an `ndarray` rather than a scalar, so I modified this to take the first element of the `F_2_1_prime` or `F_1_2_prime`, but I'm not sure if this is generalizable solution.  Not sure why those variables are arrays in the first place.

2023-08-29 16:50 UTC, alexlancaster commented
@rsingle does this look good to merge?  can you do a quick review?

2023-09-09 14:48 UTC, rsingle requested changes
Looks good

2023-09-09 14:48 UTC, rsingle commented on src/PyPop/Haplo.py
> +           af_1 = numpy.unique(a_freq1[alleles1==i])[0]  # take the first element of ndarray
```suggestion
           af_1 = numpy.unique(a_freq1[alleles1==i])[0]  # take the first element of ndarray (default behaviour)
```

2023-09-09 14:52 UTC, rsingle approved these changes
All set

2023-09-09 17:09 UTC, merged